import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#0077B6",
        alignItems: "flex-start",
        justifyContent: "flex-start",
        padding: "2.5%",
        margin: "2.5%",
        borderRadius: 10,
    },
    login: {
        flex: 1,
        backgroundColor: "#0099dd",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    loginTitle: {
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        color: "#caf0f8",
        fontSize: 60,
        fontWeight: "bold",
        margin: "20%",
        backgroundColor: "#0077B6",
        height: "9%",
        width: "70%",
        textAlign: "center",
        borderRadius: 10,
    },
    loginInput: {
        backgroundColor: "#caf0f8",
        borderRadius: 10,
        borderColor: "#002277",
        borderWidth: 1,
        color: "#002277",
        height: "5%",
        width: "80%",
        margin: "1%",
    },
    loginTouchable: {
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        margin: "5%",
        backgroundColor: "#0077B6",
        height: "5%",
        width: "20%",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#002277",
    },
    sobreTitle: {
        color: "#CAF0F8",
        fontSize: 40,
        fontWeight: "bold",
        marginVertical: "5%",
    },
    sobreSubTitle: {
        color: "#CAF0F8",
        fontSize: 30,
        fontWeight: "400",
        marginVertical: "10%",
        marginHorizontal: ".5%",
    },
    sobreText: {
        color: "#CAF0F8",
        fontSize: 20,
        marginHorizontal: "2%",
    },
    map: {
        width: "100%",
        height: "100%",
    },
    locais: {
        flex: 1,
        backgroundColor: "#0077B6",
        alignItems: "center",
        justifyContent: "center",
        padding: "2.5%",
        flexDirection: "column",
        flexWrap: "wrap",
        alignContent: "space-evenly",
        rowGap: "2.5%",
    },
    local: {
        backgroundColor: "#023E8A",
        width: "45%",
        marginHorizontal: "2.5%",
        height: "17%",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        //alignContent: "",
    },
    localImage: {
        flex: 6,
        marginTop: "5%",
        marginBottom: "5S%",
        width: "90%",
        height: "100%",
        borderRadius: 10,
        resizeMode: "cover",
    },
    localText: {
        flex: 1,
        fontSize: 15,
        alignItems: "center",
        color: "#CAF0F8",
        margin: "1%",
    },
});
